title: Nick Milliken # your name (or website title) here
logo: < image= "Nick Wedding Speech.jpg" > # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "Graduate Student at the University of Colorado Boulder persuing an MSBA on the Security Track."
  <br><br>
  "Sole Owner at Vision Quest Martial Arts"
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>

livereload: BOOL

-l, --livereload
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
